CREATE TABLE [dbo].[UserRole]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [RoleId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedOn] DATETIME2 NOT NULL, 
    [CreatedBy] UNIQUEIDENTIFIER NOT NULL, 
    [UpdatedOn] DATETIME2 NOT NULL, 
    [UpdatedBy] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_UserRole_User] FOREIGN KEY (UserId) REFERENCES [User](Id), 
    CONSTRAINT [FK_UserRole_Role] FOREIGN KEY (RoleId) REFERENCES [Role](Id)
)
